const TABLES = {
  AUDIOS: "audios",
  VIDEOS: "videos",
  CANCIONES: "canciones",
  BANDAS: "bandas",
  BANDAS_MUSICOS: "bandas_musicos",
  CIUDADES: "ciudades",
  COMENTARIOS_BANDAS: "comentarios_bandas",
  DISCOS: "discos",
  FESTIVALES: "festivales",
  FESTIVALES_BANDAS: "festivales_bandas",
  IMAGENES_BANDAS: "imagenes_bandas",
  IMAGENES_MENSAJES: "imagenes_mensajes",
  IMAGENES_FESTIVALES: "imagenes_festivales",
  IMAGENES_LUGARES: "imagenes_lugares",
  MUSICOS: "musicos",
  MENSAJES: "mensajes",
  MENSAJES_LUGARES: "mensajes_lugares",
  MENSAJES_PERSONAJES: "mensajes_personajes",
  PERSONAJES: "personajes",
  PERSONAS: "personas",
  PROPIETARIOS: "propietarios",
  PROVINCIAS: "provincias",
  USUARIOS: "usuarios",
  LUGARES: "lugares",
  LUGARES_BANDAS: "lugares_bandas",
};
module.exports = TABLES;
